steps:
  - name: gcr.io/$PROJECT_ID/terraform-with-gcloud-ssh
    env:
      - GOOGLE_PROJECT=zeepalnet
      - GOOGLE_REGION=australia-southeast1
      - TF_VAR_host=swarm-1
    args:
      - init
      - '-backend-config=bucket=zeepalnet-tfstate'
      - '-backend-config=prefix=$REPO_NAME'
    id: terraform init
  - name: gcr.io/$PROJECT_ID/terraform-with-gcloud-ssh
    env:
      - GOOGLE_PROJECT=zeepalnet
      - GOOGLE_REGION=australia-southeast1
      - TF_VAR_host=swarm-1
      - CLOUDSDK_COMPUTE_ZONE=us-west1-a
    entrypoint: bash
    args:
      - -c
      - |
          ssh swarm-1 -- hostname
    id: test
  - name: gcr.io/$PROJECT_ID/terraform-with-gcloud-ssh
    env:
      - GOOGLE_PROJECT=zeepalnet
      - GOOGLE_REGION=australia-southeast1
      - TF_VAR_host=swarm-1
      - CLOUDSDK_COMPUTE_ZONE=us-west1-a
    args:
      - apply
      - '-parallelism=1000'
      - '-auto-approve'
    id: terraform apply
timeout: 120s
